AN-55: Support for multiple models
Ankinator/ankinator pull request #54
Opened 2023-07-11 15:56 UTC by Niklas-23

Support for the selection of the model

2023-07-12 08:36 UTC, lkno0705 requested changes

2023-07-12 08:36 UTC, lkno0705 commented on flashcard_model/celery_consumer.py
> +CHAT_GPT_MODEL_KEY = "CHAT_GPT"
I think these keys should be moved to something like a config file or something like that.

2023-07-12 08:36 UTC, lkno0705 commented on flashcard_model/celery_consumer.py
> +            demo_model = DemoModel()
Instead of using all of these if clauses, i think it would be better to use pythons equivalent to a switch statement. There you would store the function pointer in a dictionary and we can then just use a get call to the dict to launch the correct function instead of "if copy-pasta"

2023-07-12 08:36 UTC, lkno0705 commented on flashcard_model/celery_consumer.py
> +            demo_model = DemoModel()
And maybe an API call to retrieve all available models would be handy for FE integration. But that depends on how this selection will be implemented in the FE.

2023-07-14 11:42 UTC, Niklas-23 commented on flashcard_model/celery_consumer.py
> +CHAT_GPT_MODEL_KEY = "CHAT_GPT"
Done

2023-07-14 11:43 UTC, Niklas-23 commented on flashcard_model/celery_consumer.py
> +            demo_model = DemoModel()
Done. I think for now we will manually exchange the keys, but later we can maybe add an endpoint for it.

2023-07-14 21:52 UTC, lkno0705 approved these changes
lgtm

2023-07-14 21:53 UTC, merged